linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errname
    #    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - goheader
    #    - goimports
    - gomnd
    - goprintffuncname
    #    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck

run:
  skip-files:
    - "_test\\.go$"
  timeout: 5m

linters-settings:
  gomnd:
    settings:
      mnd:
        ignored-functions:
          - '^strconv.*'
          - '^os.*'
